### ISSUE TITLE
msfven.sh: Syntax error: Bad for loop variable

### ISSUE THREAD

**Issue by rustempasha** [offsecginger/msfvenom_custom_encoding#2]
Hi. I've installed gcc.exe using Wine and followed all instructions on nullbyte.com
However the shell script gives this error and terminates;
msfven.sh: 63: msfven.sh: Syntax error: Bad for loop variable

Thanks.

**Comment by wayneaswilliams** [comment]
At line 63 its just creating random numbers. All of the commands are preinstalled in a kali environment. Try cloning the repository instead of copy and pasting if thats what you did previously. Id need more detail to understand why you had this issue.

**Comment by lonalore** [comment]
Run code with `./msfven.sh` instead of `sh msfven.sh`

**Comment by cacaocaca** [comment]
Yes work but for be fud depend when interaction do you use and depend the encoders do you use for example is good use shigata_ga_nai 1 interaction and afther use bf_xor always with raw output and afther use veil and add this raw .

**Comment by offsecginger** [comment]
Updates coming
